CurrentPassword:'Existing password',
NEWPassword:'New password',
AGAIN_NEWPassword:'Please re-enter new password',
LOG_OUT:'Leave log-in page',
ACCOUNT:'Account',
PASSWORD:'Password',
LOG_In:'Log in',
BREADCRUMB_Home:'Home',
COUNTRY:'Country',
Region:'Area',
Order_NUM:'Number of trips',
RENTAL_TODAY_TIME:'Rental duration',
WalletRechargeIncome:'Wallet top up revenue',
RENT_TODAY:'Rental amount',
TotalNumberUsers:'Total number of users',
TotalLengthHire:'Total rental duration',
TotalNumberOrders:'Total number of orders',
TotalRent:'Total rental amount',
TotalWalletRechargeIncome:'Total wallet deposit revenue',
NOT:'No vehicle',
BREADCRUMB_Business:'Business management',
AGENT:'Authorised agent',
AGENT_LIST:'List of authorised agents',
INTERNALLY_MANAGED:'Internally managed?',
DirectSale:'Yes',
NoDirectSale:'No',
OPERATING_STATUS:'Operating status',
ADD_AGENT:'Add agent',
NAME:'Name',
CONTACT_PERSON:'Contact person',
CONTACT_NUMBER:'Contact number',
ACTION:'Action',
ENABLE:'Enable',
DETAIL:'View',
EDIT:'Edit',
DELETE:'Delete',
OPERATOR_DISABLE:'Are you sure you want to disable this operator? ',
OPERATOR_ENABLE:'Are you sure you want to activate this operator?',
SURE:'Confirm',
CANCLELLATION:'Cancel',
DISABLED:'Disabled',
NO_DISABLE:'Enable ',
NORMAL:'Normal',
DISABLE:'Disable',
KNOW:'Noted',
OPERATOR_DELETE:'Are you sure you want to delete this agent?',
EDIT_AGENT:'Edit agent',
Basic_Information:'Basic information',
Jurisdictional_Area:'Managing area',
AGENT_NAME:'Agent name',
ADDRESS:'Address',
REMARK:'Remarks',
PLEASEREMARK:'Please add remarks ',
LOGINNAME:'Log in to account',
RESET_PASSWORD:'Reset password',
PLEASE_PASSWORD:'Please enter the password',
ABANDON_EDIT:'Discard changes',
SUBMIT:'Submit',
UNSELECTED_AREAS:'Unselected areas',
ENTER_AREA_NAME:'Please enter area name',
ALL_SELECT:'Select all',
SELECTED_AREAS:'Selected areas',
INITIAL_PASSWORD:'Initial password',
ABANDON_ADD:'Cancel',
NEXT:'Next',
DATE_CREATED:'Date created',
VIEW_AGENT:'View agent',
Provider_LIST:'List of service providers',
AGENT_BELONG:'Agent',
ADD_SERVICE_PROVIDER:'Add service provider',
AREA_BELONG:'Area',
PROVIDER_DISABLE:'Are you sure you want to disable this service provider?',
PROVIDER_DISABLE_TIP:'All staff under this service provider will also be disabled',
PROVIDER_ENABLE:'Are you sure you want to use this service provider?',
PROVIDER_DELETE:'Are you sure you want to delete this service provider?',
EDIT_SERVICE_PROVIDER:'Edit service provider',
PARKING:'Parking point',
UNSELECTED_PARK:'Unselected parking points',
SELECTED_PARK:'Selected parking points',
PARK_NAME:'Name of parking point ',
PARK_ID:'Parking point id',
PARK_TYPE:'Parking point type',
VIEW_SERVICE_PROVIDER:'View service provider',
SERVICE_PROVIDER_NAME:'Service provider name',
BREADCRUMB_Region:'Area management',
AREA_ID:'Area id',
AREA_NAME:'Area name',
ADD_Region:'Add area',
AREA_DISABLE:'Are you sure you want to disable this area?',
AREA_ENABLE:'Are you sure you want to use this area?',
AREA_DELETE:'Are you sure you want to delete this area?',
TIME_ZONE:'Time zone',
SERVICE_PHONE:'Customer service hotline',
BILLING_DETAIL:'Billing plan logic',
EDIT_Region:'Edit area',
DETAIL_Region:'Check area',
BREADCRUMB_PARK:'Parking point management',
ADD_PARK:'Add parking point',
ID_STATIC:'ID',
PARK_VEHICLE_NUMBER:'Number of vehicles in the parking point',
PARK_DISABLE:'Are you sure you want to disable this parking point?',
PARK_MAINTAINANCE:'Are you sure you want to change the status of this parking mode to "maintainance mode"?',
PARKING_MAINTAINANCE_MSG:'Parking points in maintainance mode will not be visable to users. Vehicles docked in the parking point will not be available for rent as well',
PARK_ENABLE:'Enable this parking point? ',
PARK_DELETE:'Are you sure you want to delete this parking point? ',
Charging_Dock:'Charging dock available',
Dockless_Parking:'Charging dock unavailable',
GPS_COORDINATES:'GPS coordinates',
GET_COORDINSTES:'Retrieve coordinates',
EDIT_PARK:'Edit parking point details',
PARK_SLOTS_NUMBER:'Number of parking slots',
LOCATION:'Location',
SITE_CONDITION:'Parking status',
ELECTRICITY_USAGE:'Electricity usage',
CHARGING_PORT:'Charging port',
CHARGING:'Charging',
LightsOn:'Lights on',
RCU_MODEL:'RCU model',
ONLINE:'Online',
OFFLINE:'Offline',
DCU_MODEL:'DCU model',
CARPILE_REPAIR:'Are you sure you want to change the status of this dock to "maintainance mode"?',
CARPILE_NORMAL:'Are you sure you want to restore the status of this dock to "normal"?',
CARPILE_UNLOCK:'Are you sure you want to unlock charging dock?',
VEHICLE_NUMBER:'Number of vehicles',
BACK_NORMAL:'Returned to normal',
VIEW_PARK:'View parking point',
DAILY:'Select date',
MONTHLY:'Select month',
VEHICLE_REPAIR:'Are you sure you want to change the status of this vehicle to "maintainance mode"',
VEHICLE_RENT:'Are you sure you want to change the status of this vehicle to "available"',
VEHICLE_UNLOCK:'Are you sure you want to unlock vehicle?',
ABNORMALITY:'Abnormality',
FAULT:'Fault',
VEHICLE_INFORMATION:'Vehicle details',
BREADCRUMB_VEHICLE:'Vehicle management',
VEHICLE_LIST:'Vehicle list',
PARK_POINT_BELONG:'Parking point',
VEHICLE_STATUS:'Vehicle status',
CONNECTION:'Connection',
DownloadImport:'Download template',
IMPORT_VEHICLES:'Import vehicles',
AVALIABLE:'Available',
MAINTAINANCE:'Maintainance',
WAREHOUSE:'Warehouse',
Discontinuation:'Disable',
VEHICLE_ID:'Vehicle ID',
VEHICLE_TYPE:'Vehicle type',
BATTERY:'Battery (%)',
LockCAR:'Lock vehicle',
UPDATE:'Refresh',
TRACKING_MODE:'Tracking mode',
STOP_TRACKING:'Stop tracking',
VCU_ID:'VCU ID',
VCU_MODEL:'VCU model',
FRAME_ID:'Frame ID',
SIM_CARD_NUMBER:'SIM card number',
CURRENT_LOCATION:'Current location',
LockUpThisCar:'Are you sure you want to lock this vehicle?',
FAULT_TIME:'Time of fault',
FAULT_TYPE:'Fault type',
FAULT_RECORD:'Fault record',
FAULT_Content:'Fault details',
VEHICLE_DETAIL:'Vehicle details',
ABNORMALITY_RECORD:'Abnormality record',
ABNORMALITY_TIME:'Time abnormality occurs',
ABNORMALITY_TYPE:'Abnormality type',
VEHICLE_WAREHOUSE:'Are you sure you want to change the status of this vehicle to "warehouse mode"',
VEHICLE_DISABLE:'Are you sure you want to change the status of this vehicle to disable',
MAINTAINANCE_IN:'Maintainance mode',
UNLOCK:'Unlock',
VEHICLE_EDIT:'Edit vehicle details',
BREADCRUMB_VEHICLE_TYPE:'Vehicle type management',
ADD_VEHICLE_TYPE:'Add vehicle type',
VEHICLE_NAME:'Vehicle type name',
VEHICLE_IMG:'Vehicle type logo',
ALLOW_RERURN_PARK_TYPE:'Fit for parking point',
VEHICLE_TYPE_DELETE:'Are you sure you want to delete the vehicle type?',
BREADCRUMB_Money:'Account Management',
DEPOSIT_RECORD:'Deposit record',
USER:'User',
USER_COUNTRY:'User country',
CURRENCY:'Currency',
TRANSATION_TYPE:'Transaction type',
EXPORT:'Export',
DEPOSIT_LIST_SHOW1:'Total deposits',
DEPOSIT_LIST_SHOW2:'Total withdrawals',
DEPOSIT_LIST_SHOW3:'Deposit pool',
DEPOSIT_LIST_SHOW4:'Number of deposits',
DEPOSIT_LIST_SHOW5:'Number of withdrawals',
BUSINESS_ID:'Business ID',
AMOUNT:'Amount',
CARD_NUMBER:'Card number',
TIME:'Time',
AMOUNT_SGD:'Amount (SGD)',
WALLET_UP_RECORD:'Wallet top up record',
WALLET_LIST_SHOW1:'Wallet revenue',
WALLET_LIST_SHOW2:'Number of wallet top ups',
REQUEST_REFUND:'Request for refund',
REQUEST_TIME:'Time of request',
APPROVAL_TIME:'Approval time',
REJECT_REFUND_REASON:'Reason for rejecting refund request',
PENDING_REVIEW:'Pending review',
FEUNDED:'Refunded',
REJECT_REFUND:'Refund rejected',
REFUND:'Refund',
REFUND_DEPOSIT_TO_USER:'Are you sure you want refund the user's deposit? ',
BESIDES:'Later',
REJECT_REFUND_DEPOSIT_TO_USER:'Are you sure you want to reject the user's refund request?',
BREADCRUMB_USER:'User management',
USER_LIST:'List of users',
DEPOSIT:'Deposit',
REGISTRATION_TIME:'Registration time',
USERNAME:'Name',
GENDER:'Gender',
BIRTH:'Date of birth',
USER_ACCOUNT:'User account',
PAY:'Not deposited',
NOT_PAY:'Deposited',
USER_DISABLE:'Are you sure you want to disable this user?',
USER_DISABLE_TIP:'Once disabled, user will not be able to log into the APP',
USER_CANCLE:'Log out',
MORE:'More',
UNNAMED_USER:'No personal information',
EMAIL:'Email',
USER_DETAIL:'User details',
WALLET_BALANCE:'Wallet balance',
INVIATION_CODE:'Invitation code',
CHECK_WALLET_BALANCE:'Check wallet record',
CHECK_TRIP_HISTORY:'Check trip history',
CHECK_DISCOUNT_RECORD:'Check discount record',
RENTAL_BAN:'Rental ban',
STOP_RENTAL_BAN:'Stop rental ban',
CANCLELLATION_USER:'Cancel user',
DISABLE_USER_RENTAL_CAR:'Are you sure you want to ban user from renting vehicles?',
DISABLE_USER_RENTAL_CAR_TIP:'After banning, the user will not be able to refund the deposit, top up wallet and rent any vehicles',
CANCLE_USER:'Are you sure you want to cancel user',
CANCEL_USER_TIP:'The user's wallet and deposit will be reset and cannot be refunded',
CANCEL_USER_TIP2:'Accounts that have been cancelled, can be registered again',
USER_OPERATION:'Operating user',
USER_FEEDBACK:'Feedback',
FEEDBACK_TIME:'Time of feedback',
CONTENT:'Details of feedback',
IMAGE:'Image',
VEIW_IMAGE:'View image',
BREADCRUMB_ORDER:'trip management',
ORDER_LIST:'Order list',
TRIP_ID:'Trip ID',
ORDER_STATUS:'Order status',
RENTAL_START_TIME:'Rental start time',
RENTAL_ONGOING:'Riding in progress',
CLOSE:'Shut down',
APPLY_FOR_REFUND:'Request for refund',
ORDER_DETAIL:'Order details',
FEEDBACK:'Feedback',
COST:'Cost',
CLOSE_TRIP:'Closed trip',
END_TRIP:'End trip',
PROCESS_RESULTS:'Conculsion',
PROCESS_INSTRUCTIONS:'Remarks',
RENTAL_START_ADDRESS:'Rental location',
RENTAL_END_TIME:'Rental end time',
RENTAL_END_ADDRESS:'End location',
RENTAL_DURATION:'Rental duration',
TRIP_DISTANCE:'Trip distance',
TRIP_ChargeTime:'Charging duration',
ACTUAL_COST:'Actual cost',
DISCOUNT:'Discount',
MOVEMENT_TRACK:'Travelling route',
CLOSE_ORDER:'Are you sure you want to close the trip ?',
CLOSE_ORDER_TIP:'After trip closes, user doesn't have to pay and the status of this vehicle changes to "warehouse mode", ',
END_ORDER:'Are you sure you want to end the trip ?',
END_ORDER_TIP:'After trip ends, user must pay and the status of this vehicle change to "warehouse mode"',
REFUND_USER:'Are you sure you want to permit the refund to the user? ',
REFUND_AMOUNT:'Refund amount',
REFUND_INSTRUCTIONS:'Remarks',
REFUND_NOT_MORE_THEN_ACTUAL:'The amount of the refund cannot exceed the actual amount of payment',
REJECT_REFUND_ORDER_TO_USER:'Are you sure you do not want to permit the refund to the user?',
RENTAL_VEHICLE_INFORMATION:'Trip detail',
DRIVING_COST:'Trip cost',
BREADCRUMB_REFUND:'Refund request',
SELECT_ALL:'All',
ACTIVITY:'Manage promotion',
BREADCRUMB_RACTIVITY:'Promotion',
ACTIVITY_TIME:'Promotion duration',
ADD_ACTIVITY:'Add promotion',
ACTIVITY_NAME:'Promotion name',
ACTIVITY_TYPE:'Promotion type',
ACTIVITY_STATUS:'Promotion status',
ACTIVITY_START_TIME:'promotion start date',
ACTIVITY_END_TIME:'promotion end date',
INVITE:'Invitation bonus',
BOUNS:'Send promotion',
ACTIVITY_ENABLE:'Enable this promotion?',
ACTIVITY_DISABLE:'Disable this promotion?',
ACTIVITY_DISABLE_TIP:'The coupons that have been sent are still valid after promotion period has ended',
ACTIVITY_DELETE:'Are you sure you want to delete this promotion?',
SingaporeDollar:'Amount (SGD)',
REWARD_USER:'Reward user',
INVITER:'Inviter',
REWARD_AMOUNT:'Reward amount',
INVITEE:'Invitee',
LOCATION_TIME:'Local time',
DISCOUNT_AMOUNT:'Discount amount',
TICKET_NUMBER:'Number of coupons',
UNLIMITED:'Unlimited',
LIMITED:'Limited',
UNITS:'Units',
EACH_PERSON_LIMIT_DISCOUNT_NUMBER:'Limit the number of times each user can use this discount',
DISCOUNT_VALIDITY:'Discount validity',
FIXED:'Fixed',
SELECTED_AREA:'Selected area',
SEND_PERSON_HAVE_ORDER_LIST:'Only issue to last order of user in this area',
DISCOUNT_IMAGE:'Discount image',
EDIT_ACTIVITY:'Edit promotion',
COUPONS_VALIDITY:'Discount validity(local time)',
ACTIVITY_DETAIL:'View promotion',
DISCOUNT_RECORDS:'Discount records',
RELATED_TRIP_ID:'Related trip id',
REDEEM:'Redeem',
USE:'Use',
CHARGING_RECORDS:'Charging record',
CHARGING_START_TIME:'Charging start time',
CHARGING_DETAIL:'Charging status',
CHARGE_IN:'Start charging',
BEFORE_CHARGE_ELECTRICITY:'Battery (%) before charging',
AFTER_CHARGE_ELECTRICITY:'Battery (%) after charging',
OTA_PLAN:'OTA plan',
Component_Name:'Component name',
MODEL:'Model',
Firmware_Version:'Firmware version',
Firmware_Upgrade:'Upgrade firmware',
CurrentFirmwareVersion:'Current firmware version',
New_Firmware_Upload:'Firmware upload',
File_Selecte:'Select document',
NO_File_Selected:'No file selected',
NewFirmwareVersion:'New firmware version number',
Version_Description:'Firmware version description',
Upgrade_Date:'Upgrade date',
Upgrade_DETAIL:'Upgrade status',
Download_Again:'Download again',
Download_Again_Tip:'Download instructions sent to device(s), please hold on.',
OldFirmwareVersion:'Original firmware version',
UpFirmwareVersion:'Upgraded firmware version',
UpFirmwareVersionDown:'Downloading upgraded firmware version',
UpFirmwareVersionRE:'Upgraded firmware version manual',
Download:'Download',
OTA_DELETE:'Are you sure you want to delete this firmware?',
FirmwareVersionMaintain:'Firmware maintenance',
Firmware_VersionNum:'Firmware version number',
Version_Description2:'Firmware manual',
DATE_ADD:'Increase time',
OTA_ADD:'Upload firmware',
WALLET_TIP_MSG:'Please go to top-up tab to edit',
SYSTEM_Setting:'System settings',
DEPOSITSetting:'Deposit & top up settings',
ADD_DEPOSIT:'Add deposit & top up option',
TOP_UP:'Top up',
WALLET_UP_AMOUNT:'Wallet top up amount',
DEPOSIT_AMOUNT:'Deposit',
DEPOSIT_SETTING_DELETE:'Are you sure you want to delete deposit settings?',
BILLING_PLAN:'Billing plan',
BILLING_TYPE:'Billling type',
ADDBILLING_PLAN:'Add billing plan',
BILLING_PLAN_NAME:'Billing plan name',
STATUS:'Status',
BILLING_DELETE:'Are you sure you want to delete this billing plan?',
BILLING_DISABLE:'Are you sure you want to disable this billing plan',
feeErrorMsg_1:'Cap price should be equal or less than calculated amount',
feeErrorMsg_2:'The cap time will be the end of the (name of the previous rate). Blank means no cap.',
feeErrorMsg_3:'Capped amount should be less than or equal to the total accumulated fees',
feeErrorMsg_4:'Cap amount and cap time must either be blank together or be filled together.',
BILLING_TIME_BASED:'Time based',
BILLING_TIME_LADDER_BASED:'Time ladder based',
BILLING_PLAN_LOGIC:'Billing plan logic',
ADDBILLING_PLAN_EDIT:'Edit billing plan',
ADDBILLING_PLAN_DETAIL:'View billing plan',
RECEIVING_ACCOUNTSetting:'Payment accounts',
RECEIVING_ACCOUNT:'Account income',
RECEIVING_CURRENCY:'Receiving currency',
ACCOUNT_ID:'Account ID',
RECEIVING_ACCOUNT_ADD:'Add payment account',
ANNOUNCEMENT_URL:'Please key in URL link details',
ANNOUNCEMENT:'Announcement management',
ADD_ANNOUNCEMENT:'Add announcement',
ANNOUNCEMENT_TITLE:'Announcement subject',
ANNOUNCEMENT_DESCRIPT:'Announcement description',
ANNOUNCEMENT_CONTENT:'Announcement content',
ANNOUNCEMENT_IMAGE:'Subject image',
ANNOUNCEMENT_TIME_INTERVAL:'Set publish date',
PUBLISH_TIME:'Publish date',
ANNOUNCEMENT_YES:'No',
ANNOUNCEMENT_NO:'Yes',
ANNOUNCEMENT_DELETE:'Are you sure you want to delete this announcement?',
STAFFSetting:'Staff management',
ROLESetting:'Role management',
ADD_ROLE:'Add role',
ROLE_NAME:'Role name',
ROLELIST:'List of roles',
ROLE_DELETE:'Are you sure you want to delete this role?',
PERMISSION:'Authority',
SELECT_ASSIGN_PERMISSIONS:'Please select the permission',
ADD_ROLE2:'Add role',
STAFF_ACCOUNT_Setting:'Employee account management',
STAFF_USERNAME:'Username',
LAST_LOGIN_TIME:'Last login time',
LAST_LOGIN_IP:'Last login IP',
Operation_Log:'Operation log',
BUSINESS_ENTITY_BELONG:'Business entity',
Activity_NumUpperLimit:'Each user is limited to less than voucher amount.',
CHARGING_DOCK_PARK_NOT_IN_SELECT_AREA:'The location of charging dock is not within selected area',
DOCKLESS_PARKING_NOT_IN_SELECT_AREA:'The location of free parking is not within selected area',
NOT_DRAW_AREA:'Please mark area',
PLEASE_SELECT_VEHICLE:'Select vehicle',
NOT_IMPORT_IMG:'Image not uploaded',
IMG_IMPORT_IN:'Image is uploading',
IMPORT_IMG_ERROR:'Image upload failure',
IMPORT_IMG_TYPE:'Image in wrong format',
Can_Not_Be_Empty:'Please do not leave this empty',
PLEASE_SELECT_AREA:'Please select area',
COUPON_MORE_THAN_ACTIVITY_END:'Discount validity should later than promotion end date',
IMPORT_SUCCESS:'Import success',
IMPORT_ERROR:'Import failure',
TWO_PASSWORD:'Both passwords do not match',
NoData:'No data input',
CanNotEnterSpaces:'Please do not leave this empty',
PleaseEnterAPositiveInteger:'Please enter a whole number',
PleaseEnterTheCorrectAmount:'Please key in the correct amount.',
PleaseEnterACombinationOfNumbersAndLetters:'Please key in number and letter combination.',
ChANG_PASSWORD:'Change password',
TIMEMIN:'Minutes',
TODAY:'Today',
VEHICLE:'Vehicle',
ORDER:'Order',
TOTAL:'Total',
Previous:'Previous step',
EDIT_VEHICLE_TYPE:'Edit vehicle model',
StartRequestDate:'Application start date',
EndRequestDate:'Application expiry date',
DCU_ID:'DCU number',
EDIE_ROLE:'Edit role',
ADD_STAFF:'Add staff',
ROLE:'Role',
EDIT_ANNOUNCEMENT:'Edit announcement',
ENTER_PARK_NAME:'Please enter parking point name.',
USER_ENABLE:'Are you sure you want to enable this account?',
RESTORE_USER_RENTAL_CAR:'Are you sure you want to restore this account?',
BILLING_ENABLE:'Are you sure you want to use this billing plan?',
STAFF_DELETE:'Are you sure you want to delete this staff?',
EXCEPTION_INFORMATION:'Information abnormal',
FAULT_INFORMATION:'Information malfunction',
RATE :'Exchange rate',